CREATE TABLE [dbo].[Account_TestPushtoProduction_20161103]
(
[UpsertType] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[RecordtypeId] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DW_ContactId__c] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[contactid] [uniqueidentifier] NULL,
[FullName] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FirstName] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[LastName] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Patron_ID__c] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Patron_Status__c] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Customer_Type__c] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Customer_Status__c] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BillingStreet] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BillingCity] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BillingState] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BillingPostalCode] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BillingCountry] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PersonMailingStreet] [int] NULL,
[PersonMailingCity] [int] NULL,
[PersonMailingState] [int] NULL,
[PersonMailingPostalCode] [int] NULL,
[PersonMailingCountry] [int] NULL,
[PersonHomePhone] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PersonMobilePhone] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Biz_Other_Phone__c] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Fax] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PAH_Email__pc] [varchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[PersonEmail] [varchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VIP_Code__c] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Internet_Profile__c] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Customer_Comments__c] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Donor_ID__c] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Export_Datetime__c] [datetime] NULL,
[dbLastUpdated] [datetime] NULL,
[IsBusinessAccount] [bit] NULL
)
GO
