CREATE TABLE [etl].[ProdCopy_User]
(
[Id] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Name] [nvarchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CreatedDate] [datetime] NULL,
[CreatedById] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LastModifiedDate] [datetime] NULL,
[LastModifiedById] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SystemModstamp] [datetime] NULL,
[IsActive] [bit] NULL,
[Username] [nvarchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LastName] [nvarchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FirstName] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CompanyName] [nvarchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Division] [nvarchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Department] [nvarchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Title] [nvarchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Street] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[City] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[State] [nvarchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PostalCode] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Country] [nvarchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Email] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Phone] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Fax] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MobilePhone] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Alias] [nvarchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CommunityNickname] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TimeZoneSidKey] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UserRoleId] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LocaleSidKey] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ReceivesInfoEmails] [bit] NULL,
[ReceivesAdminInfoEmails] [bit] NULL,
[EmailEncodingKey] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProfileId] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UserType] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LanguageLocaleKey] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EmployeeNumber] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DelegatedApproverId] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ManagerId] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LastLoginDate] [datetime] NULL,
[OfflineTrialExpirationDate] [datetime] NULL,
[OfflinePdaTrialExpirationDate] [datetime] NULL,
[UserPermissionsMarketingUser] [bit] NULL,
[UserPermissionsOfflineUser] [bit] NULL,
[UserPermissionsAvantgoUser] [bit] NULL,
[UserPermissionsCallCenterAutoLogin] [bit] NULL,
[UserPermissionsMobileUser] [bit] NULL,
[UserPermissionsSFContentUser] [bit] NULL,
[UserPermissionsInteractionUser] [bit] NULL,
[UserPermissionsChatterAnswersUser] [bit] NULL,
[ForecastEnabled] [bit] NULL,
[UserPreferencesActivityRemindersPopup] [bit] NULL,
[UserPreferencesEventRemindersCheckboxDefault] [bit] NULL,
[UserPreferencesTaskRemindersCheckboxDefault] [bit] NULL,
[UserPreferencesReminderSoundOff] [bit] NULL,
[UserPreferencesDisableAllFeedsEmail] [bit] NULL,
[UserPreferencesDisableFollowersEmail] [bit] NULL,
[UserPreferencesDisableProfilePostEmail] [bit] NULL,
[UserPreferencesDisableChangeCommentEmail] [bit] NULL,
[UserPreferencesDisableLaterCommentEmail] [bit] NULL,
[UserPreferencesDisProfPostCommentEmail] [bit] NULL,
[UserPreferencesDisableAutoSubForFeeds] [bit] NULL,
[UserPreferencesApexPagesDeveloperMode] [bit] NULL,
[UserPreferencesHideCSNGetChatterMobileTask] [bit] NULL,
[UserPreferencesDisableMentionsPostEmail] [bit] NULL,
[UserPreferencesDisMentionsCommentEmail] [bit] NULL,
[UserPreferencesHideCSNDesktopTask] [bit] NULL,
[UserPreferencesDisCommentAfterLikeEmail] [bit] NULL,
[UserPreferencesDisableLikeEmail] [bit] NULL,
[UserPreferencesDisableMessageEmail] [bit] NULL,
[UserPreferencesOptOutOfTouch] [bit] NULL,
[UserPreferencesDisableBookmarkEmail] [bit] NULL,
[UserPreferencesDisableSharePostEmail] [bit] NULL,
[ContactId] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AccountId] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CallCenterId] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Extension] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FederationIdentifier] [nvarchar] (512) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AboutMe] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CurrentStatus] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FullPhotoUrl] [nvarchar] (1024) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SmallPhotoUrl] [nvarchar] (1024) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DigestFrequency] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DefaultGroupNotificationFrequency] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Mark_Code__c] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Full_User_ID__c] [nvarchar] (1300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ETLLoad] [datetime] NULL CONSTRAINT [DF__ProdCopy___ETLLo__671F4F74] DEFAULT (getdate())
)
GO
