CREATE TABLE [src_Sandbox].[Task]
(
[Id] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WhoId] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WhatId] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Subject] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ActivityDate] [date] NULL,
[Status] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Priority] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IsHighPriority] [bit] NULL,
[OwnerId] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Description] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Type] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IsDeleted] [bit] NULL,
[AccountId] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IsClosed] [bit] NULL,
[CreatedDate] [datetime] NULL,
[CreatedById] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LastModifiedDate] [datetime] NULL,
[LastModifiedById] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SystemModstamp] [datetime] NULL,
[IsArchived] [bit] NULL,
[CallDurationInSeconds] [int] NULL,
[CallType] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CallDisposition] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CallObject] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ReminderDateTime] [datetime] NULL,
[IsReminderSet] [bit] NULL,
[RecurrenceActivityId] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IsRecurrence] [bit] NULL,
[RecurrenceStartDateOnly] [date] NULL,
[RecurrenceEndDateOnly] [date] NULL,
[RecurrenceTimeZoneSidKey] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RecurrenceType] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RecurrenceInterval] [int] NULL,
[RecurrenceDayOfWeekMask] [int] NULL,
[RecurrenceDayOfMonth] [int] NULL,
[RecurrenceInstance] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RecurrenceMonthOfYear] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RecurrenceRegeneratedType] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TaskSubtype] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Soft_Delete__c] [bit] NULL,
[Activity_Type__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Meeting_Location__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Did_you_meet_with_Decision_Maker__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Purchase__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Prospect_Needs__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Recommended_Products__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Next_Steps__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Full_Task_ID__c] [nvarchar] (1300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[koreps__Activity_Category__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[koreps__Activity_Sub_Category__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[koreps__Campaign_Id__c] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[koreps__ColorCode__c] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[koreps__Date_Completed__c] [datetime] NULL,
[koreps__Deal_Sheet_ID__c] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[koreps__Due_Time__c] [datetime] NULL,
[koreps__KORE_Touchpoint_ID__c] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[koreps__Premium_Deal_ID_del__c] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[koreps__Secondary_Name_ID__c] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[koreps__Short_Description__c] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[koreps__Subject__c] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[koreps__Task_Type__c] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[koreps__Touchpoint__c] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[koreps__Consumption_ID__c] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[koreps__SyncPriority__c] [float] NULL,
[ETL_CreatedDate] [datetime] NOT NULL CONSTRAINT [DF__Task__ETL_Create__7EE1CA6C] DEFAULT (getdate())
)
GO
